config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'home#show'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  resources :users, only: %i[new create]
  resources :questions do
    resources :answers, only: %i[create update destroy], shallow: true do
      collection do
        get :like_answers
      end
    end
    collection do
      get :bookmark_questions
    end
  end
  resources :evidences, only: %i[index create edit update destroy]
  resources :bookmark_questions, only: %i[create destroy]
  resources :like_answers, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :categories, only: %i[index create edit update destroy]
  resources :tags, only: %i[index create edit update destroy]
  resources :authors, only: %i[index create edit update destroy]
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :question_evidences
  has_many :evidences, through: :question_evidences
  has_many :article_tags, as: :articable, dependent: :destroy
  has_many :tags, through: :article_tags, as: :articable

  validates :title, presence: true, length: { maximum: 60 }
  validates :body, presence: true, length: { maximum: 1_000 }

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags.to_a - sent_tags.to_a
    new_tags = sent_tags.to_a - current_tags.to_a

    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    new_tags.each do |new|
      new_question_tag = Tag.find_or_create_by(name: new)
      self.tags << new_question_tag
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :require_login, only: %i[index show]
  before_action :find_question, only: %i[edit update destroy]

  def index
    @questions = Question.all.includes(:user).order(created_at: :desc).page(params[:page])
  end

  def new
    @question = Question.new
    @categories = Category.all
  end

  def create
    @question = current_user.questions.build(question_params)
    sent_tags = params[:question][:name].split(',')
    if @question.save
      @question.save_tag(sent_tags)
      redirect_to questions_path, success: t('defaults.message.created', item: Question.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_created', item: Question.model_name.human)
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = @question.answers.includes(:user).order(created_at: :desc)
  end

  def edit
    @categories = Category.all
    @tag_list = @question.tags.pluck(:name).join(',')
  end

  def update
    sent_tags = params[:question][:name].split(',')
    if @question.update(question_params)
      @old_relations = ArticleTag.where(articable_id: @question.id)
      @old_relations.each do |relation|
        relation.delete
      end
      @question.save_tag(sent_tags)
      redirect_to @question, alert: t('defaults.message.updated', item: Question.model_name.human)
    else
      flash.now[:alert] = t('defaults.message.not_updated', item: Qustion.model_name.human)
    end
  end

  def destroy
    @question.destroy!
    redirect_to questions_path, success: t('defaults.message.deleted', item: Question.model_name.human)
  end

  def bookmark_questions
    @bookmark_questions = current_user.bookmark_questions.includes(:user).order(created_at: :desc)
  end

  private

  def find_question
    @question = current_user.questions.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, :category_id, tag_ids: [])
  end
end

app/views/questions/_bookmark.html.erb
<%= link_to bookmark_questions_path(question_id: question.id), id: "js-bookmark-button-for-question-#{question.id}", class:"float-right", method: :post, remote: true do %>
<%= icon 'fa-regular', 'bookmark' %>
<% end %>

app/views/questions/_bookmark_button.html.erb
<% if current_user.bookmark?(question) %>
  <%= render 'unbookmark', { question: question } %>
<% else %>
  <%= render 'bookmark', { question: question } %>
<% end %>

app/views/questions/_crud_menus.html.erb
<ul>
  <li>
    <%= link_to edit_question_path(question), id: "button-edit-#{question.id}" do %>
      <%= icon 'fa', 'pen' %>
    <% end %>
  </li>
  <li>
    <%= link_to question_path(question), id: "button-delete-#{question.id}", method: :delete, data: { confirm: t('defaults.message.delete_confirm') } do %>
      <%= icon 'fas', 'trash' %>
    <% end %>
  </li>
</ul>

app/views/questions/_form.html.erb
<div class="block w-full max-w-5xl justify-self-center px-3 mt-10">
  <%= form_with model: question, local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="md:flex md:items-center mb-6">
      <div class="md:w-1/6">
        <%= f.label :title, class:"block text-gray-700 font-bold md:text-left mb-1 md:mb-0 pr-4" %>
      </div>  
      <div class="md:w-5/6">
        <%= f.text_field :title, class:"bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-green-500" %>
      </div>
    </div>
    <div class="md:flex md:items-center mb-6">
      <div class="md:w-1/6">
        <%= f.label :body, class:"block text-gray-700 font-bold md:text-left mb-1 md:mb-0 pr-4" %>
      </div>
      <div class="md:w-5/6">
        <%= f.text_area :body, rows: 10, class:"bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-green-500" %>
      </div>
    </div>
    <div class="md:flex md:items-center mb-6">
      <div class="md:w-1/6">
        <%= f.label :tag, class:"block text-gray-700 font-bold md:text-left mb-1 md:mb-0 pr-4" %>
      </div>
      <div class="md:w-5/6">
        <%= f.text_field :name, value: tag_list, placeholder:",で区切ってください", class:"bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-green-500" %>
      </div>
    </div>
    <div class="md:flex md:items-center mb-6">
      <div class="md:w-1/6">
        <%= f.label :category, class:"block text-gray-700 font-bold md:text-left mb-1 md:mb-0 pr-4" %>
      </div>
      <div class="md:w-5/6">
        <div class="inline-block relative w-66">
          <%= f.collection_select :category_id, @categories, :id, :name, {prompt: "カテゴリーを選択してください"}, class:"block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline" %>
          <div class="pointer-events-none absolute inset-y-0 right-0 px-2 flex items-center text-gray-700">&#9660;</div>
        </div>
      </div>
    </div>
    
    <div class="md:flex md:items-center">
      <div class="md:w-1/6"></div>
      <div class="md:w-5/6">
        <%= f.submit class:"shadow bg-green-500 hover:bg-green-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" %>
      </div>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<div class="max-w-sm w-11/12 rounded overflow-hidden shadow-lg justify-self-center mb-20">
  <div class="flex items-center justify-center w-full h-48">
    <% if question.category_id.present? %>
      <%= image_tag "question_image.png", alt: "category_image", class: "rounded-full h-24 w-24" %>
    <% else %> 
      <%= image_tag "question_image.png", alt: "category_image", class: "rounded-full h-24 w-24" %>
    <% end %>
  </div>
  <div class="px-6 py-4">
    <div class="font-bold text-xl mb-2 flex items-center"><%= link_to question.title, question_path(question) %></div>
    <% if current_user.present? %>
      <% if current_user.own?(question) %>
        <%= render 'crud_menus', question: question %>
      <% else %>
        <%= render 'bookmark_button', question: question %>
      <% end %>
    <% end %>
    <p class="text-gray-700 text-base overflow-hidden h-24">
      <%= question.body %>
    </p>
  </div>
  <div class="px-6 pt-4 pb-2">
    <% question.tags.each do |tag| %>
      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#<%= tag.name %></span>
    <% end %>
  </div>
</div>

app/views/questions/_unbookmark.html.erb
<%= link_to bookmark_question_path(current_user.bookmark_questions.find_by(question_id: question.id)), id: "js-bookmark-button-for-question-#{question.id}", class:"float-right", method: :delete, remote: true do %>
  <%= icon 'fa-solid', 'bookmark' %>
<% end %>

app/views/questions/bookmark_question.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <form>
        <div class="input-group mb-3">
          <input class="form-control" placeholder="検索ワード" type="search" />
          <div class="input-group-append">
            <input type="submit" value="検索" class="btn btn-primary" />
          </div>
        </div>
      </form>
    </div>
  </div>

  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @bookmark_questions.present? %>
          <%= render @bookmark_questions %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/bookmark_questions.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <form>
        <div class="input-group mb-3">
          <input class="form-control" placeholder="検索ワード" type="search" />
          <div class="input-group-append">
            <input type="submit" value="検索" class="btn btn-primary" />
          </div>
        </div>
      </form>
    </div>
  </div>

  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @bookmark_questions.present? %>
          <%= render @bookmark_questions %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<% content_for(:title, @question.title) %>
<div class="grid grid-cols-1 place-content-center">
  <div class="text-2xl font-bold justify-self-center px-3 mt-10 mb-10"><%= t('.head') %></div>
  <%= render 'form', { question: @question, tag_list: @tag_list } %>
</div>

app/views/questions/index.html.erb
<% content_for(:title, t('.title')) %>
<!-- 検索フォーム -->
<div class="grid grid-cols-1 md:max-w-screen-md lg:max-w-screen-lg xl:max-w-screen-xl mx-auto px-2 place-items-end">
  <form class="w-full max-w-md mt-2 mb-5">
    <div class="flex item-center">
      <input placeholder="検索ワード" type="search" class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-green-500">
        <div class="px-1">
          <input type="submit" value="検索" class="shadow bg-green-500 hover:bg-green-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded">
        </div>
    </div>
  </form>
</div>

<!-- 質問一覧ページの説明 -->


<!-- 掲示板一覧 -->
<% if @questions.present? %>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 place-content-center md:max-w-screen-md lg:max-w-screen-lg xl:max-w-screen-xl mx-auto">
    <%= render @questions %>
  </div>
<% else %>
  <p><%= t('.no_result') %></p>
<% end %>

<!-- ページネーション -->
<%= paginate @questions %>

app/views/questions/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="grid grid-cols-1 place-content-center">
  <div class="text-2xl font-bold justify-self-center px-3 mt-10 mb-10"><%= t('.head') %></div>
  <%= render 'form', { question: @question, tag_list: @tag_list } %>
</div>

app/views/questions/show.html.erb
<% content_for(:title, @question.title) %>
<div>
  <div>
    <div>
      <h1><%= t('.title') %></h1>
      <!-- 質問内容 -->
      <article>
        <div>
          <div>
            <div>
              <h3><%= @question.title %></h3>
              <%= render 'crud_menus', question: @question if current_user && current_user.own?(@question) %>
              <ul>
                <li>by <%= @question.user.name %></li>
                <li><%= l @question.created_at, format: :long  %></li>
              </ul>
            </div>
          </div>
          <%= simple_format(@question.body) %>
        </div>
      </article>
    </div>
  </div>

  <!-- 回答フォーム -->
  <% if current_user %>
    <%= render 'answers/form', { question: @question, answer: @answer } %>
  <% end %>

  <!-- 回答エリア -->
  <%= render 'answers/answers', { answers: @answers } %>
</div>