config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'home#show'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  resources :users, only: %i[new create]
  resources :questions do
    resources :answers, only: %i[create update destroy], shallow: true do
      collection do
        get :like_answers
      end
    end
    collection do
      get :bookmark_questions
    end
  end
  resources :evidences, only: %i[index create edit update destroy]
  resources :bookmark_questions, only: %i[create destroy]
  resources :like_answers, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :categories, only: %i[index create edit update destroy]
  resources :tags, only: %i[index create edit update destroy]
  resources :authors, only: %i[index create edit update destroy]
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update]
  
  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profile_path, success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit
    end
  end

  def show; end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:email, :name, :avatar)
  end
end

app/views/profiles/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="grid grid-cols-1 place-content-center">
  <div class="text-2xl font-bold justify-self-center px-3 mt-10 mb-10"><%= t('.head') %></div>
  <div class="block w-full max-w-5xl justify-self-center px-3 mt-10">
    <%= form_with model: @user, url: profile_path, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/6">
          <%= f.label :email, class:"block text-gray-700 font-bold md:text-left mb-1 md:mb-0 pr-4" %>
        </div>
        <div class="md:w-5/6">
          <%= f.email_field :email, class:"bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-green-500" %>
        </div>
      </div>
      <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/6">
          <%= f.label :name, class:"block text-gray-700 font-bold md:text-left mb-1 md:mb-0 pr-4" %>
        </div>
        <div class="md:w-5/6">
          <%= f.text_field :name, class:"bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-green-500" %>
        </div>
      </div>
      <div class="md:flex md:items-center">
      <div class="md:w-1/6"></div>
      <div class="md:w-5/6 flex items-center justify-between">
        <%= f.submit class:"shadow bg-green-500 hover:bg-green-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" %>
        <%= link_to t("defaults.password_reset"), '/password_resets/new', class:"inline-block text-green-500 font-bold" %>
      </div>
    </div>     
    <% end %>
  </div>
</div>

app/views/profiles/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h1 class="float-left mb-5"><%= t('.title') %></h1>
      <%= link_to t('defaults.edit'), edit_profile_path, class: 'btn btn-success float-right' %>
      <table class="table">
        <tr>
          <th scope="row"><%= t(User.human_attribute_name(:email)) %></th>
          <td><%= current_user.email %></td>
        </tr>
        <tr>
          <th scope="row"><%= t(User.human_attribute_name(:name)) %></th>
          <td><%= current_user.name %></td>
        </tr>
      </table>
    </div>
  </div>
</div>