config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'home#show'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  resources :users, only: %i[new create]
  resources :questions do
    resources :answers, only: %i[create update destroy], shallow: true do
      collection do
        get :like_answers
      end
    end
    collection do
      get :bookmark_questions
    end
  end
  resources :evidences, only: %i[index create edit update destroy]
  resources :bookmark_questions, only: %i[create destroy]
  resources :like_answers, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :categories, only: %i[index create edit update destroy]
  resources :tags, only: %i[index create edit update destroy]
  resources :authors, only: %i[index create edit update destroy]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user && user&.admin? # 管理者じゃなかったらこのメソッドを抜ける

    can :access, :rails_admin # 管理者画面のアクセス許可
    can :manage, :all # 管理権限許可
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :like_answers, dependent: :destroy

  validates :body, presence: true, length: { maximum: 250 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :tag
  belongs_to :articable, polymorphic: true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :sources, through: :source_authors
  has_many :source_authors

  validates :name, presence: true, length: { maximum: 255 }
end

app/models/bookmark_question.rb
class BookmarkQuestion < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :user_id, uniqueness: { scope: :question_id }
end

app/models/category.rb
class Category < Taxonomy
  has_many :evidences, through: :article_tags, source: :articable, source_type: "Evidence"
  has_many :questions, through: :article_tags, source: :articable, source_type: "Question"
end

app/models/evidence.rb
class Evidence < ApplicationRecord
  belongs_to :user
  has_many :question_evidences
  has_many :questions, through: :question_evidences
  has_many :evidence_sources
  has_many :sources, through: :evidence_sources
  has_many :article_tags, as: :articable, dependent: :destroy
  has_many :tags, through: :article_tags, as: :articable

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }
end

app/models/evidence_source.rb
class EvidenceSource < ApplicationRecord
  belongs_to :evidence
  belongs_to :source
end

app/models/like_answer.rb
class LikeAnswer < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :answer

  validates :user_id, uniqueness: { scope: :answer_id }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :question_evidences
  has_many :evidences, through: :question_evidences
  has_many :article_tags, as: :articable, dependent: :destroy
  has_many :tags, through: :article_tags, as: :articable

  validates :title, presence: true, length: { maximum: 60 }
  validates :body, presence: true, length: { maximum: 1_000 }

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags.to_a - sent_tags.to_a
    new_tags = sent_tags.to_a - current_tags.to_a

    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    new_tags.each do |new|
      new_question_tag = Tag.find_or_create_by(name: new)
      self.tags << new_question_tag
    end
  end
end

app/models/question_evidence.rb
class QuestionEvidence < ApplicationRecord
  belongs_to :question
  belongs_to :evidence
end

app/models/source.rb
class Source < ApplicationRecord
  has_many :evidence_sources
  has_many :evidences, through: :evidence_sources
  has_many :source_authors
  has_many :authors, through: :source_authors
  
  enum evidence_level:{ ★☆☆☆: 1, ★★☆☆: 2, ★★★☆: 3, ★★★★: 4 }
  enum source_type:{ 論文: 0, 書籍: 1 }

  validates :title, presence: true, length: { maximum: 60 }
  validates :body, presence: true, length: { maximum: 65_000 }
end

app/models/source_author.rb
class SourceAuthor < ApplicationRecord
  belongs_to :author
  belongs_to :source
end

app/models/tag.rb
class Tag < Taxonomy
  has_many :article_tags, dependent: :destroy
  has_many :evidences, through: :article_tags, source: :articable, source_type: "Evidence"
  has_many :questions, through: :article_tags, source: :articable, source_type: "Question"
end

app/models/taxonomy.rb
class Taxonomy < ApplicationRecord
  validates :name, presence: true, uniqueness: { scope: :type }, length: { maximum: 16 }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :questions
  has_many :answers
  has_many :evidences
  has_many :bookmark_questions, dependent: :destroy
  has_many :bookmark_questions_questions, through: :bookmark_questions, source: :question
  has_many :like_answers, dependent: :destroy
  has_many :like_answers_answers, through: :like_answers, source: :answer

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, uniqueness: true, allow_nil: true

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true, length: { maximum: 255 }

  enum role: { general: 0, admin: 1 }

  def own?(object)
    id == object.user_id
  end

  def bookmark(question)
    bookmark_questions_questions << question
  end

  def unbookmark(question)
    bookmark_questions_questions.destroy(question)
  end

  def bookmark?(question)
    bookmark_questions_questions.include?(question)
  end

  def like_answer(answer)
    like_answers_answers << answer
  end

  def unlike_answer(answer)
    like_answers_answers.destroy(answer)
  end

  def like_answer?(answer)
    like_answers_answers.include?(answer)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login, only: %i[show]

  def show; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '')
    base_title = 'コノタメ'

    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end
end

app/views/shared/_before_login_header.html.erb
<header class="bg-white md:flex md:justify-between md:items-center md:px-4 md:py-3">
  <div class="flex items-center justify-between px-4 py-3 md:p-0 relative z-10 bg-white">
    <div>
      <%= link_to root_path do %>
        <%= image_tag 'logo.png', class:"h-14" %>
      <% end %>
    </div>
    
    <div id="main" class="md:hidden">
      <span id="openmenu" onclick="openMenu()" class="text-4xl font-semibold cursor-pointer hover:text-green-700">&#9776;</span>
      <span id="closemenu" onclick="closeMenu()" class="hidden text-4xl font-semibold cursor-pointer hover:text-red-400">&times;</span>
    </div>
  </div>
  <div id="mainsleep" class="hidden absolute">
    <span class="fixed inset-0 h-full w-full bg-black opacity-50 cursor-default"></span>
  </div>       
  <nav id="menu0" class="hidden block relative z-10 bg-white rounded px-3 pt-2 pb-4 md:flex md:p-0">
    <%= link_to 'コノタメとは', "#", class:"block md:inline-block px-5 py-1 text-gray-700 font-semibold rounded hover:bg-gray-300" %>
    <%= link_to '質問', questions_path, class:"mt-1 block md:inline-block px-5 py-1 text-gray-700 font-semibold rounded hover:bg-gray-300 md:mt-0 md:ml-2" %>
    <%= link_to 'エビデンス', evidences_path, class:"mt-1 block md:inline-block px-5 py-1 text-gray-700 font-semibold rounded hover:bg-gray-300 md:mt-0 md:ml-2" %>
    <%= link_to link_to (t 'defaults.register'), new_user_path, class:"mt-1 block md:inline-block px-5 py-1 text-gray-700 font-semibold rounded hover:bg-gray-300 md:mt-0 md:ml-2" %>
    <%= link_to (t 'defaults.login'), login_path, class:"mt-1 block md:inline-block px-5 py-1 text-gray-700 font-semibold rounded hover:bg-gray-300 md:mt-0 md:ml-2 md:rounded-full md:bg-green-500 md:text-white md:ml-5" %>
  </nav>
</header>

<script> 
  var menu0 = document.getElementById("menu0");
  var main = document.getElementById("main");
  var closemenu = document.getElementById("closemenu");
  var openmenu = document.getElementById("openmenu");
  var mainsleep = document.getElementById("mainsleep");
  
  // show the menu
  function openMenu() {
      menu0.classList.remove('hidden');
      closemenu.classList.remove('hidden');
      openmenu.classList.add('hidden');
      mainsleep.classList.remove('hidden');
  }

  // make the menu "go away"
  function closeMenu() {
      menu0.classList.add('hidden');
      closemenu.classList.add('hidden');
      openmenu.classList.remove('hidden');
      mainsleep.classList.add('hidden');
  }
</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="bg-red-100 border border-red-400 text-red-700 px-3 py-3 mt-3 mb-3 rounded relative" role="alert">
    <% object.errors.full_messages.each do |msg| %>
      <span class="block sm:inline"><%= msg %></span>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "danger" %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 m-3 rounded relative" role="alert">
      <strong class="font-bold"><%= message %></strong>
    </div>
  <% else %>
  <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 m-3 rounded relative" role="alert">
    <strong class="font-bold"><%= message %></strong>
  </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="grid grid-cols-8 gap-4 text-center py-20">
    <div class="md:col-span-3 col-span-8 px-4 py-5 justify-self-center">
      <%= link_to root_path do %>
        <%= image_tag "footer__logo.png" %>
      <% end %>
    </div>
    <div class="md:col-start-4 md:col-span-2 col-span-8 py-5">
      <div class="text-lg text-gray-900 py-1">サービス</div>
      <ul class="text-sm text-gray-700">
        <li class="py-1">質問一覧</li>
        <li class="py-1">エビデンス一覧</li>
      </ul>
    </div>
    <div class="md:col-start-6 md:col-span-2 col-span-8 py-5">
      <div class="text-lg text-gray-900 py-1">サポート</div>
      <ul class="text-sm text-gray-700">
        <li class="py-1">お知らせ</li>
        <li class="py-1"><a href="/policy">利用規約</a></li>
        <li class="py-1"><a href="/privacy_policy">プライバシーポリシー</a></li>
        <li class="py-1"><a href="/privacy_policy">お問合せ</a></li>
      </ul>
    </div>
  
    <div class="col-span-8 text-xs text-gray-700 py-10">&copy;2022 ５マイクロ, LLC.</div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="bg-white md:flex md:justify-between md:items-center md:px-4 md:py-3">
  <div class="flex items-center justify-between px-4 py-3 md:p-0 z-10 relative bg-white">
    <div>
      <%= link_to root_path do %>
        <%= image_tag 'logo.png', class:"h-14" %>
      <% end %>
    </div>
    
    <div id="main" class="md:hidden">
      <span id="openmenu" onclick="openMenu()" class="text-4xl font-semibold cursor-pointer hover:text-green-700">&#9776;</span>
      <span id="closemenu" onclick="closeMenu()" class="hidden text-4xl font-semibold cursor-pointer hover:text-red-400">&times;</span>
    </div>
  </div>
  <div id="mainsleep" class="hidden absolute">
    <span class="fixed inset-0 h-full w-full bg-black opacity-50 cursor-default"></span>
  </div>      
  <nav id="menu0" class="hidden block z-10 relative px-3 pt-2 pb-4 md:flex md:p-0 bg-white rounded">
    <%= link_to 'コノタメとは', "#", class:"block md:inline-block px-5 py-1 text-gray-700 font-semibold rounded hover:bg-gray-300" %>
    <%= link_to '質問', questions_path, class:"mt-1 block md:inline-block px-5 py-1 text-gray-700 font-semibold rounded hover:bg-gray-300 md:mt-0 md:ml-2" %>
    <%= link_to 'エビデンス', evidences_path, class:"mt-1 block md:inline-block px-5 py-1 text-gray-700 font-semibold rounded hover:bg-gray-300 md:mt-0 md:ml-2" %>
    <%= link_to 'マイページ', '#', class:"mt-1 block md:inline-block px-5 py-1 text-gray-700 font-semibold rounded hover:bg-gray-300 md:mt-0 md:ml-2" %>
    <%= link_to (t 'defaults.logout'), logout_path, method: :delete, class:"mt-1 block md:inline-block px-5 py-1 text-gray-700 font-semibold rounded hover:bg-gray-300 md:mt-0 md:ml-2 md:rounded-full md:bg-green-500 md:text-white md:ml-5" %>
  </nav>
</header>

<script> 
  var menu0 = document.getElementById("menu0");
  var main = document.getElementById("main");
  var closemenu = document.getElementById("closemenu");
  var openmenu = document.getElementById("openmenu");
  var mainsleep = document.getElementById("mainsleep");
  
  // show the menu
  function openMenu() {
      menu0.classList.remove('hidden');
      closemenu.classList.remove('hidden');
      openmenu.classList.add('hidden');
      mainsleep.classList.remove('hidden');
  }

  // make the menu "go away"
  function closeMenu() {
      menu0.classList.add('hidden');
      closemenu.classList.add('hidden');
      openmenu.classList.remove('hidden');
      mainsleep.classList.add('hidden');
  }
</script>

app/views/supports/top.html.slim
| トップページ