config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'home#show'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  resources :users, only: %i[new create]
  resources :questions do
    resources :answers, only: %i[create update destroy], shallow: true do
      collection do
        get :like_answers
      end
    end
    collection do
      get :bookmark_questions
    end
  end
  resources :evidences, only: %i[index create edit update destroy]
  resources :bookmark_questions, only: %i[create destroy]
  resources :like_answers, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :categories, only: %i[index create edit update destroy]
  resources :tags, only: %i[index create edit update destroy]
  resources :authors, only: %i[index create edit update destroy]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :like_answers, dependent: :destroy

  validates :body, presence: true, length: { maximum: 250 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = current_user.answers.build(answer_params)
    @answer.save
  end

  def destroy
    @answer = current_user.answers.find(params[:id])
    @answer.destroy!
  end

  def like_answers
    @like_answers = current_user.like_answers_answers.includes(:user).order(created_at: :desc)
  end

  def update
    @answer = current_user.answers.find(params[:id])
    if @answer.update(answer_update_params)
      render json: { answer: @answer }, status: :ok
    else
      render json: { answer: @answer, errors: { messages: @answer.errors.full_messages } }, status: :bad_request
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body).merge(question_id: params[:question_id])
  end

  def answer_update_params
    params.require(:answer).permit(:body)
  end
end

app/views/answers/_answer.html.erb
<tr id="answer-<%= answer.id %>">
  <td>
    <h3><%= answer.user.name %></h3>
    <div id="js-answer-<%= answer.id %>">
      <%= simple_format(answer.body) %>
    </div>
    <div id="js-textarea-answer-box-<%= answer.id %>" style="display: none;">
      <textarea id="js-textarea-answer-<%= answer.id %>" class="form-control mb-1"><%= answer.body %></textarea>
      <button class="js-button-edit-answer-cancel" data-answer-id="<%= answer.id %>">キャンセル</button>
      <button class="js-button-answer-update" data-answer-id="<%= answer.id %>">更新</button>
    </div>
  </td>
  <td>
  <% if current_user && current_user.own?(answer) %>
    <%= render 'answers/crud_menus', answer: answer %>
  <% else %>
    <%= render 'answers/like_button', answer: answer, cookies: @cookies %>
  <% end %>
  </td>
</tr>

app/views/answers/_answers.html.erb
<div>
  <div>
    <table id="js-table-answer">
      <%= render answers %>
    </table>
  </div>
</div>

app/views/answers/_crud_menus.html.erb
<ul class='crud-menu-btn list-inline float-right'>
  <li class="list-inline-item">
    <span data-answer-id=<%= answer.id %> class="js-edit-answer-button">
      <%= icon 'fa', 'pen' %>
    </span>
  </li>
  <li class="list-inline-item">
  <%= link_to answer_path(answer), class: 'js-delete-answer-button', method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, remote: true do %>
    <%= icon 'fa-solid', 'trash' %>
  <% end %>
  </li>

app/views/answers/_form.html.erb
<div>
  <div>
    <%= form_with model: answer, url: [question, answer], id: 'new_answer', local: false do |f| %>
      <%= f.label :body %>
      <%= f.text_area :body, id: 'js-new-answer-body', row: 4, placeholder: Answer.human_attribute_name(:body) %>
      <%= f.submit t('defaults.post') %>
    <% end %>
  </div>
</div>

app/views/answers/_like.html.erb
<%= link_to like_answers_path(answer_id: answer.id), id: "js-like-button-for-answer-#{answer.id}", class:"float-right", method: :post, remote: true do %>
  <%= icon 'far', 'star' %>
<% end %>

app/views/answers/_like_button.html.erb
<% if current_user.present? %>
  <% if current_user.like_answer?(answer) %>
    <%= render 'answers/unlike', { answer: answer } %>
  <% else %>
    <%= render 'answers/like', { answer: answer } %>
  <% end %>
<% else %>
  <% if cookies.nil? %>
    <%= render 'answers/like', { answer: answer } %>
  <% else %>
    <% if cookies.split(",").map(&:to_i).include?(answer.id) %>
      <span class="far fa-heart like" id="like-<%= answer.id %>"></span>
    <% else %>
      <%= render 'answers/like', { answer: answer }  %>
    <% end %>
  <% end %>
<% end %>

app/views/answers/_unlike.html.erb
<% if current_user.present? %>
  <%= link_to like_answer_path(current_user.like_answers.find_by(answer_id: answer.id)), id: "js-like-button-for-answer-#{answer.id}", class:"float-right", method: :delete, remote: true do %>
    <%= icon 'fas', 'star' %>
  <% end %>
<% else %>
  <span class="fa-solid fa-star like" id="like-<%= answer.id %>"></span>
<% end %>

app/views/answers/create.js.erb
$("#error_messages").remove()
<% if @answer.errors.present? %>
  $("#new_answer").prepend("<%= j(render('shared/error_messages', object: @answer)) %>")
<% else %>
  $("#js-table-answer").prepend("<%= j(render('answers/answer', answer: @answer)) %>")
  $("#js-new-answer-body").val('')
<% end %>

app/views/answers/destroy.js.erb
$("tr#answer-<%= @answer.id %>").remove()

app/views/answers/likes.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <form>
        <div class="input-group mb-3">
          <input class="form-control" placeholder="検索ワード" type="search" />
          <div class="input-group-append">
            <input type="submit" value="検索" class="btn btn-primary" />
          </div>
        </div>
      </form>
    </div>
  </div>

  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @like_answers_answers.present? %>
          <%= render @like_answers_answers %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>